# Generated by Django 4.2.4 on 2024-01-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_choice_id_alter_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
